### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Samuar** [serianox/DKMS-dummy_hcd#1]
Hello,

From this project and your [website](https://www.duboucher.eu/gadgetfs-ubuntu.html), it isn't obvious what license this code is available to use? Could you please specify one?

Thanks in advance,

Sam

**Comment by serianox** [comment]
Hi,

Thanks for asking this question. The answer is easy, but not obvious.

Since the content of this repository is:
1. too small to involve creative process,
2. based on the documentation and user guides,
it cannot be protected under the rules of intellectual property, and can be considered as belonging to the public domain.

**Comment by Samuar** [comment]
Thank you very much - both for the clarification and the repo itself.

Sam
